---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by houn.
--- DateTime: 2019/4/21 12:52
---
---@param n number @this function is cal 阶乘
local function fact(n)
    if n == 0 then
        return 1
    end
    return  n * fact(n - 1)
end

print("Enter a number:")
local a = io.read("*n")
print(fact(a))