---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jow.hou.
--- DateTime: 2019/4/25 14:41
---
local poly = {
    color = "blue",
    thickness = 2,
    { x = 0, y = 0 }, --polyline[1]
    nppoints = 4,
    { x = 2, y = 2 }, --polyline[2]
    { x = 5, y = 6 }, --polyline[3]
    [4] = { x = 7, y = 8 },
    [6] = { x = 10, y = 10 }
}

for i, v in ipairs(poly) do
    print(v, v.x, v.y)
end
for i, v in pairs(poly) do
    print(v)
end

local t1 = {
    [1] = 1,
    [3] = 3
}
print(#t1)

local t2 = { 1, 2, 3, 4, 5, 6, 7 }
local t3 = {}
table.insert(t3, 1)
table.move(t2, 1, #t2, 2)
table.move(t2, 1, #t2, 2, t3)
for i, v in ipairs(t2) do
    print(t2[i])
end

for i, v in ipairs(t3) do
    print(t3[i])
end
print("end")

sunday = "monday"
monday = "sunday"
t = { sunday = "monday", [sunday] = "monday" }
print(t.sunday, t[sunday], t[t.sunday])

a = {}
a.a = a
a.a.a.a = 3
print((a.a or {}))

function multi(t, x)
    local result = 0
    for i, v in ipairs(t) do
        result = result + v * x ^ (i - 1)
    end
    return result
end

print(multi({ 1, 2, 3, 4 }, 2))

function multi1(t,x)
    local result = t[#t]
    for i = 1, #t - 1 do
        result = result*x + t[#t - i]
    end
    return result
end

print(multi1({ 1, 2, 3, 4 }, 2))