---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by houn.
--- DateTime: 2019/5/8 23:03
---
local lines = {}
for line in io.lines() do
    lines[#lines + 1] = line
end

table.sort(lines)

for i, v in ipairs(lines) do
    io.write(v, "\n")
end