---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by houn.
--- DateTime: 2019/4/22 22:21
---This file is to practice eight queen question
---

local N = 8 -- 棋盘的大小 8*8local
local totalResult = 0

local t1 = os.clock()
--检查(n, c) 会不会被攻击
---@param table table
---@param n number
---@param c number
---@return boolean
---
local function checkAttack(table, n, c)
    for i = 1, n - 1 do
        if (table[i] == c) or
                (table[i] - i == c - n) or --行列式
                (table[i] + i == c + n) then
            return false
        end
    end
    return true
end

---@param table table
local function printTable(table)
    for i = 1, N do
        for j = 1, N do
            if j == table[i] then
                io.write("O ")
            else
                io.write("X ")
            end
        end
        io.write("\n")
    end
    io.write("\n")
    totalResult = totalResult + 1
end

---@param table table
---@param n number
local function addQueen(table, n)
    if n > N then
        printTable(table)
    else
        for c = 1, N do
            if checkAttack(table, n, c) then
                table[n] = c
                addQueen(table, n + 1)
            end
        end
    end
end

addQueen({}, 1)
print("Total answer:" .. totalResult)
print("Method1 time:", os.clock() - t1)

---@param table table
---@param n number
---return table
local function insertNumber(t, n)
    local result = {}
    for i = 1, #t + 1 do
        result[i] = t
        table.insert(result[i], i, n)
    end
    return result
end

---@param t1 table
---@param t2 table
---@return table
local function mergeTable(t1, t2)
    for i = 1, #t2 do
        table.insert(t1, #t1 + i, t2[i])
    end
end

---@param table table
---@param n number
---@return table
local function arrangement(t, n)
    if n > N then
        return t
    end
    local temp = {}
    for i = 1, #t + 1 do
        temp = mergeTable(temp, insertNumber(t[i], n))
    end
    arrangement(temp, n + 1)
end




